### PR TITLE
DocumentDetails: fix error notification

### LINKED ISSUE #837: ui: frontsite Document details page broken when doc is restricted
To reproduce:
* create a restricted document
* log in as a patron
* visit the Document details page

The page shows a JS error.

Expected:
The page should show you are not authorized.

### PR DESCRIPTION
**Pull request by KonstantinaStoikou**
Closes #837

### CODE REVIEW

File: ui/src/components/Forbidden/Forbidden.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
+import React, { Component } from 'react';
+import { Link } from 'react-router-dom';
+import { Grid, Button, Icon } from 'semantic-ui-react';
+
+export class Forbidden extends Component {
+  render() {
+    return (
+      <div className="frontsite">
```
Comment (topless) [inline ui/src/components/Forbidden/Forbidden.js:8]: Is `frontsite` used? If it is not replacing the whole frontsite I find it a bit generic, maybe we can use something more specific for example `fs-forbidden` or just `forbidden` nested inside the proper `frontsite`! ping @kprzerwa!

File: ui/src/components/index.js [hunk 2]
```diff
@@ -7,6 +7,7 @@ export { DocumentAuthors } from './Document';
 export { EmailLink } from './EmailLink';
 export { EmptyMessage } from './EmptyMessage';
 export { Error } from './Error';
+export { Forbidden } from './Forbidden/Forbidden';
```
Comment (topless) [inline ui/src/components/index.js:10]: Since we export it from `index.js` it can be just `export { Forbidden } from './Forbidden';` like the rest

**Review by topless — APPROVED** [review]

File: ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentsDetails.js [hunk 3]
```diff
@@ -63,7 +63,14 @@ export default class DocumentsDetails extends Component {
   ];
 
   render() {
-    const { isLoading, error, documentDetails } = this.props;
+    const { isLoading, hasError, error, documentDetails } = this.props;
```
Comment (topless) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentsDetails.js:66]: @ntarocco, @kprzerwa, @zzacharo, instead of explicitly checking in every component maybe we can have a HOC that will handle the errors and their relevant components

Comment (ntarocco) [reply ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentsDetails.js:66]: yep, maybe for @kprzerwa refactoring in the new repo, since this affects and it is applicable only to the main details pages components routes.

**Review by ntarocco — APPROVED** [review]
