### PR TITLE
Fix ui forms

### LINKED ISSUE #752: fix the submit button behaviour for forms
Problem: Now it is possible to submit twice, there is no feedback about the submit which is ongoing.

Expected:
When clicking on submit, the button should be in the loading state, the whole form should be blocked against making any changes (f.e. also loading state) before the response comes back, and the users get's redirected.

### PR DESCRIPTION
**Pull request by ntarocco**
- removes `ES_DELAY` when saving forms
- replaces the various `setTimeout` with common `delay` function that returns a Promise
- replaces `window.open` with `goTo` where it makes sense
- refactors a few Promises to use async/await instead
- closes #752

There a still a couple of setTimeout left and weird behaviour on submit, in the components in Patron Profile pages: I couldn't change it easily because they require some refactoring.
We will do them later on.

### CODE REVIEW

**Review by kpsherva — APPROVED** [review]

File: ui/src/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js [hunk 1]
```diff
@@ -28,12 +28,16 @@ export class InternalLocationForm extends Component {
     ]);
   };
 
-  updateInternalLocation = (pid, data) => {
-    return internalLocationApi.update(pid, data);
+  updateInternalLocation = async (pid, data) => {
+    const response = await internalLocationApi.update(pid, data);
+    await delay();
```
Comment (topless) [inline ui/src/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js:33]: While here we inject the delay in the component, in the `internalLocation.delete` the delay is part of the actions which I think is the place we should put all the delays in order to avoid the pitfall of having them twice (not sure if this is the case anywhere).

**Review by topless — APPROVED** [review]

File: ui/src/forms/core/BaseForm/BaseForm.js [hunk 2]
```diff
@@ -24,15 +23,13 @@ export class BaseForm extends Component {
...
-        this.props.sendSuccessNotification(
-          'Success!',
-          this.props.successSubmitMessage
-        );
-        if (this.props.successCallback) {
-          this.props.successCallback(response, submitButton);
-        }
-      }, ES_DELAY);
+      this.props.sendSuccessNotification(
+        'Success!',
```
Comment (zzacharo) [inline ui/src/forms/core/BaseForm/BaseForm.js:27]: nit: I like this refactoring here and I would say that even the "Success" argument should be handled from the function `sendSuccessNotification`. It was like that before as it was required from the action for the notification part. But I think is clearer if the function just accepts a function. Also, in that case I would say the `successSubmitMessage` is redundant.

**Review by zzacharo — APPROVED** [review]

File: ui/src/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js (hunk 1 above)
Comment (topless) [reply ui/src/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js:33]: I checked the code and there are reducers only for `locationList` and `internalLocationList` so, the components is the only place.

Comment (ntarocco) [reply ui/src/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js:33]: Discussed by voice.

File: ui/src/forms/core/BaseForm/BaseForm.js (hunk 2 above)
Comment (ntarocco) [reply ui/src/forms/core/BaseForm/BaseForm.js:27]: I agree. Honestly I started to do it, but then I saw it was touching all forms, so better to do it in another PR if it is ok with you.
