### PR TITLE
Vocabularies

### LINKED ISSUE #543: Vocabularies
For many of the fields in the different records, we need to implement vocabularies so that the user can choose a value from a list via a simple `<select>` component. Examples could be: list of languages, list of countries, list of subjects...

**Requirements**
* as a sys admin, I need to be able to import a new vocabulary (set of values) for a given field.
* as a sys admin, I need to easily delete/edit/add a new item to a vocabulary list
* as a librarian, I need to be able to select a value from a vocabulary for a given record field

**Tasks**
* identify all the fields that need a vocabulary in ILS and identify any potential exception
* design and implement the solution, backend
Proposal: have a CLI command to import/sync a JSON for a given vocabulary. JSON structure:
```
[{
    type: language,
    id: "en",
    value: "en",
    text: "English"
}, ...]
```
Index this list in a dedicated ES index accessible from Invenio, e.g. `/api/vocabularies/?q=type:language`. No records needed. Similar to Patron implementation.
* for these fields, add the dropdowns with search and autocompletion in the frontend app

### PR DESCRIPTION
**Pull request by equadon**
* Backend: added `/api/vocabularies` endpoint
* Backoffice: updated forms to use vocabularies
* Upgraded NPM packages

Closes #543 

Followup issues:
* Delete tag record: https://github.com/inveniosoftware/invenio-app-ils/issues/611
* Add document licenses: https://github.com/inveniosoftware/invenio-app-ils/issues/613

### CODE REVIEW

File: invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js [hunk 1]
```diff
@@ -0,0 +1,329 @@
...
+    return (
+      <div className={classes} role="alert" aria-live="polite" aria-atomic>
+        {_flag}
+        {_text}
+      </div>
+    );
+  };
+}
+
+export const FLAG_NAMES = [
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js]: is there any chance we can take them from a vocabulary?

File: invenio_app_ils/ui/src/invenio_app_ils/forms/core/VocabularyField.js [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+      fieldPath,
+      label,
+      multiple,
+      serializer,
+      type,
+      ...uiProps
+    } = this.props;
+    const { isLoading, options } = this.state;
+    const noResultsMessage = isLoading
+      ? 'Loading vocabularies...'
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/forms/core/VocabularyField.js]: for the user's perspective I would display `Loading options...` I don't think they will know what is a vocabulary

File: invenio_app_ils/ui/src/semantic-ui/site/collections/form.overrides [hunk 3]
```diff
@@ -2,6 +2,12 @@
          Site Overrides
 *******************************/
 
+.field .ui.dropdown {
+  .ui.label.error {
+    background-color: @dropdownMissingColor;
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/semantic-ui/site/collections/form.overrides]: I suggest to rename it to `@dropdownErrorColor`

File: invenio_app_ils/cli.py [hunk 4]
```diff
@@ -845,9 +846,15 @@ def create_userprofile_for(email, username, full_name):
     "--skip-demo-data", is_flag=True, help="Skip creating demo data."
 )
 @click.option("--skip-patrons", is_flag=True, help="Skip creating patrons.")
+@click.option(
+    "--skip-vocabularies",
+    is_flag=True,
```
[the remark this answers is not in the document]
Comment (equadon) [reply invenio_app_ils/cli.py:851]: No, it will import the demo vocabularies by default and only ignore it if you provide `--skip-vocabularies`.

File: invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js (hunk 1 above)
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js]: The problem is that semantic UI throws an exception if it gets an incorrect flag name so I need to compare with the list of valid names. I just saw that semantic exports the list of valid flag names so I'll use that instead.

**Edit**: I've tried to import the available flag names from https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/elements/Flag/Flag.js but with no success. Any ideas?

File: INSTALL.rst [hunk 5]
```diff
@@ -170,3 +170,37 @@ In addition to the normal ``docker-compose.yml``, this one will start:
 - UWSGI (application container)
 - Celery (background task worker)
 - Flower (Celery monitoring)
+
+
+Vocabularies
+------------
+Vocabularies are indexed using Elasticsearch and can be indexed from a JSON
```
[the remark this answers is not in the document]
Comment (equadon) [reply INSTALL.rst:177]: Yes, I agree but it probably shouldn't be in `INSTALL.rst`. It would make more sense to put that general terminology documentation somewhere else.

File: invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js (hunk 1 above)
Comment (ntarocco) [reply invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js]: If you don't like it, we can get rid of the flags! :)

File: invenio_app_ils/vocabularies/cli.py [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+    """Index JSON-based vocabularies in Elasticsearch."""
+    if not force:
+        click.confirm(
+            "Are you sure you want to index the vocabularies?",
+            abort=True
+        )
+    source = "json"
+    index_count = 0
+    for filename in filenames:
+        print('indexing vocabularies in {}...'.format(filename))
```
Comment (ntarocco) [inline invenio_app_ils/vocabularies/cli.py]: nit: Is `print` ok to be used? Isn't it better to use `click.echo`?

File: invenio_app_ils/vocabularies/data/author_affiliation_identifier_schemes.json [hunk 7]
```diff
@@ -0,0 +1,107 @@
...
+  },
+  {
+    "type": "author_affiliation_identifier_scheme",
+    "key": "Editor",
+    "text": "Editor"
+  },
+  {
+    "type": "author_affiliation_identifier_scheme",
+    "key": "HostingInstitution",
+    "text": "Hosting Institution"
```
Comment (ntarocco) [inline invenio_app_ils/vocabularies/data/author_affiliation_identifier_schemes.json]: isn't this one the `author type`? https://schema.datacite.org/meta/kernel-4.3/include/datacite-contributorType-v4.xsd

File: invenio_app_ils/vocabularies/data/author_types.json [hunk 8]
```diff
@@ -0,0 +1,12 @@
+[
+  {
+    "type": "author_type",
```
Comment (ntarocco) [inline invenio_app_ils/vocabularies/data/author_types.json:3]: this one maybe just `affiliation_type`?

File: invenio_app_ils/vocabularies/sources/base.py [hunk 9]
```diff
@@ -0,0 +1,47 @@
...
+    def __init__(self, source_type):
+        """Initialize vocabulary source."""
+        self.source_type = source_type
+
+    @staticmethod
+    def validate(vocabulary):
+        """Validate vocabulary."""
+        if not isinstance(vocabulary, Vocabulary):
+            raise VocabularyError(
+                "{!r} is not a vocabulary".format(vocabulary))
```
Comment (ntarocco) [inline invenio_app_ils/vocabularies/sources/base.py]: Didn't know about the `!r`! :)

Comment (equadon) [reply invenio_app_ils/vocabularies/sources/base.py]: Completely useless now since I didn't include the `__str__` and `__repr__` implementations.. :)

File: INSTALL.rst (hunk 5 above)
[the remark this answers is not in the document]
Comment (ntarocco) [reply INSTALL.rst:177]: Good point! I propose that we will move it when we will write the documentation for it.
https://github.com/inveniosoftware/invenio-app-ils/issues/222

File: invenio_app_ils/config.py [hunk 10]
```diff
@@ -678,12 +678,12 @@ def _(x):
         record_class=Vocabulary,
         record_serializers={
             "application/json": (
-                "invenio_records_rest.serializers" ":json_v1_response"
+                "invenio_app_ils.records.serializers:json_v1_response"
```
Comment (ntarocco) [inline invenio_app_ils/config.py:681]: @equadon I had to change the serializers otherwise it was not working, 500 when fetching the vocabularies... was it working with you with default serializers?
Python 3 in your venv?

File: invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js [hunk 11]
```diff
@@ -2,6 +2,7 @@ import React, { Component } from 'react';
 import PropTypes from 'prop-types';
 import { VocabularyField } from '../core';
 import { Dropdown, Flag } from 'semantic-ui-react';
+import { names as FLAG_NAMES } from 'semantic-ui-react/dist/commonjs/elements/Flag/Flag';
```
Comment (ntarocco) [inline invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js:5]: @equadon @kprzerwa this is the only way I found to avoid the list.
Given that there are no future releases (kind of dead project), I guess it is pretty safe... And also if the path is not found, there is a build error...
They exported values in TypeScript but in JS :(

What do you think?

File: invenio_app_ils/vocabularies/data/alternative_title_types.json [hunk 12]
```diff
@@ -1,22 +1,22 @@
 [
   {
     "type": "alternative_title_type",
-    "key": "AlternativeTitle",
+    "key": "ALTERNATIVE_TITLE",
```
Comment (ntarocco) [inline invenio_app_ils/vocabularies/data/alternative_title_types.json:4]: @equadon @kprzerwa what do you thing to use the uppercase instead? The advantage it that checking the record metadata we can guess what is vocabulary value and what is user input...

File: invenio_app_ils/ui/src/invenio_app_ils/forms/core/VocabularyField.js [hunk 13]
```diff
@@ -37,19 +35,11 @@ export class VocabularyField extends React.Component {
...
-        options.push({
-          key: '',
-          value: '',
-          text: '-',
-        });
-      }
       for (let hit of response.data.hits) {
         options.push(serializer(hit));
       }
-      if (this._mounted) {
```
Comment (ntarocco) [inline invenio_app_ils/ui/src/invenio_app_ils/forms/core/VocabularyField.js]: @equadon why did you need this `mounted`?

File: invenio_app_ils/config.py (hunk 10 above)
Comment (equadon) [reply invenio_app_ils/config.py:681]: Hm strange. Yes, everything was working when I was running it but this change seems good.

File: invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js (hunk 11 above)
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/forms/components/CountryField.js:5]: Thank you! I tried to make that work but wasn't successful. It's not optimal but given how the exports work we don't have many choices.

File: invenio_app_ils/vocabularies/data/alternative_title_types.json (hunk 12 above)
Comment (equadon) [reply invenio_app_ils/vocabularies/data/alternative_title_types.json:4]: We use uppercase elsewhere for constants in ILS so we should continue doing that I think.

Edit: I also updated the language keys to be uppercase to keep it consistent.

File: invenio_app_ils/ui/src/invenio_app_ils/forms/core/VocabularyField.js (hunk 13 above)
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/forms/core/VocabularyField.js]: Now that accordion fields are optimized to only render if they are open it might be that you open a vocabulary field inside an accordion and if you close it before the vocabulary field has called `this.setState` you'll get an error that you can't update the state for an unmounted component.
