### PR TITLE
Checkout loader fix

### LINKED ISSUE #210: PR 198  fixes
there are few fixes to be done after https://github.com/inveniosoftware/invenio-app-ils/pull/198
- [x] reimplement the `setTimeout` function to be run with the loader "loading" state while waiting for timeout - the timeout is set to handle latency of elasticsearch propagation, after discussions `setTimeout` seems to be the easiest solution, not introducing additional complexity to the ui code
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265204258
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265207372 (the list of API urls - normalisation)
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265210550 <- to be discussed
- [x] the error handling has to be implemented for the functionality this PR provides
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265237331
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265228829 (confirmed with others, that it is ok way)

### PR DESCRIPTION
**Pull request by kpsherva**
Fixed comments to  PR 198
( closes #210 )

### CODE REVIEW

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js [hunk 1]
```diff
@@ -43,6 +44,27 @@ export default class ItemsSearch extends Component {
     }
   };
 
+  _onPasteHandler = e => {
+    let queryString = e.clipboardData.getData('Text');
+    this.executeSearch(queryString).then(data => {
+      this.checkoutItem(this.props.items.hits[0], this.props.patron).then(
+        () => {
+          this.clearResults();
+          // setTimeout(() => {
```
Comment (ntarocco) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: Do we keep this commented out? Or maybe just forgotten?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/state/actions.js [hunk 2]
```diff
@@ -17,6 +14,7 @@ export const fetchPatronCurrentLoans = patronPid => {
           .qs()
       )
       .then(response => {
+        console.log('GOT RESPONSE');
```
Comment (ntarocco) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/state/actions.js]: I think this is to be removed... even if it should be stripped out by webpack...

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/state/reducer.js [hunk 3]
```diff
@@ -12,6 +12,7 @@ export default (state = initialState, action) => {
     case IS_LOADING:
       return { ...state, isLoading: true };
     case SUCCESS:
+      console.log('DIspatched success');
```
Comment (ntarocco) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/state/reducer.js]: Same here

File: invenio_app_ils/ui/src/invenio_app_ils/common/api/documents/document.js [hunk 4]
```diff
@@ -34,6 +34,9 @@ class QueryBuilder {
   }
 
   withKeyword(keyword) {
+    if (!keyword) {
+      throw TypeError('Keyword argument missing');
+    }
```
Comment (equadon) [inline invenio_app_ils/ui/src/invenio_app_ils/common/api/documents/document.js:39]: Thanks for adding that!

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js [hunk 5]
```diff
@@ -43,6 +43,24 @@ export default class ItemsSearch extends Component {
     }
   };
 
+  _onPasteHandler = e => {
+    let queryString = e.clipboardData.getData('Text');
+    this.executeSearch(queryString).then(data => {
+      this.checkoutItem(this.props.items.hits[0], this.props.patron).then(
```
Comment (equadon) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js:49]: If the pasted barcode results in no matches this will raise an error. Is that something we should guard against?

**Review by equadon — COMMENTED** [review]
Needs a rebase on #204

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js (hunk 5 above)
Comment (kpsherva) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js:49]: yes, the bug was introduces with changes of error handling, I will create a ticket for it

**Review by equadon — DISMISSED** [review]

**Review by topless — DISMISSED** [review]

**Review by ntarocco — DISMISSED** [review]
@kprzerwa if you take into account @topless comment, IMHO feel free to merge afterwards without checking it again.

**Review by equadon — DISMISSED** [review]
