### PR TITLE
backoffice ui: fix errors when pasting barcode

### LINKED ISSUE #253: backoffice ui: Wrong barcode pasted raises an error
If the pasted barcode results in no matches this will raise an error. Is that something we should guard against?

_Originally posted by @equadon in https://github.com/inveniosoftware/invenio-app-ils/pull/240_

### PR DESCRIPTION
**Pull request by equadon**
* Fix error when pasting barcode with no results
* Show notification on barcode search error
* Bug fix: Notifications are now displayed properly if a JSON response is returned from Invenio (e.g. `InvalidQueryRESTError` in Invenio Records REST)
* Fixes #253

### CODE REVIEW

**Review by zzacharo — DISMISSED** [review]

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js [hunk 1]
```diff
@@ -32,28 +34,24 @@ export default class ItemsSearch extends Component {
...
+    this.setState({ currentQueryString: '' });
     this.executeSearch(queryString).then(data => {
-      if (this.props.items.hits[0].status === 'LOANABLE') {
-        this.checkoutItem(this.props.items.hits[0], this.props.patron).then(
-          () => {
-            this.clearResults();
-            this.fetchUpdatedCurrentLoans(this.props.patron);
-          }
-        );
+      if (hits && hits[0].status === 'LOANABLE') {
```
Comment (vlad-bm) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: Shouldn't we also check if hits[0] is truthy? Otherwise .status will be called on undefined.

Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: Yes, you're right. Thanks for spotting that!

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js [hunk 2]
```diff
@@ -37,23 +38,25 @@ export default class ItemsSearch extends Component {
...
     let queryString = e.clipboardData.getData('Text');
     this.executeSearch(queryString).then(data => {
-      if (this.props.items.hits[0].status === 'LOANABLE') {
-        this.checkoutItem(this.props.items.hits[0], this.props.patron).then(
-          () => {
-            this.clearResults();
-            this.fetchUpdatedCurrentLoans(this.props.patron);
-          }
-        );
+      const { patron } = this.props;
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: I think you could assign in outside the `then` or as class attribute if you don't like the long `this.props.patron`, because in this case it gets assigned every time on paste, but the patron does not change.

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js [hunk 3]
```diff
@@ -37,23 +38,25 @@ export default class ItemsSearch extends Component {
...
+      const { hits } = this.props.items;
+      if (!_isEmpty(hits) && hits[0].metadata.status === 'LOANABLE') {
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: actually now if think about it, we should make sure that it returns only one hit and if it returns more raise an error, or at least do not check out automatically, I know it is not likely as the barcodes are unique, but maybe it is worth it to check anyway. WDYT?

Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: Can we do anything to guarantee that barcodes are unique in the database?

If we can't then yes I agree. Perhaps we can do a checkout if there is only one hit and show the search results if there are multiple hits?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js [hunk 4]
```diff
@@ -37,23 +38,25 @@ export default class ItemsSearch extends Component {
   };
 
   executeSearch = queryString => {
+    queryString = queryString || this.props.queryString;
+    this.setState({ prevSearchQuery: queryString });
+
     if (queryString) {
       return this.fetchItems(queryString);
```
[the remark this answers is not in the document]
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: I think this function needs to return a promise for the `onPasteHandler` but I will clean it up so it always returns a promise and that `executeSearch` is not called if it's empty.

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js [hunk 5]
```diff
@@ -37,29 +38,31 @@ export default class ItemsSearch extends Component {
...
-            this.fetchUpdatedCurrentLoans(this.props.patron);
-          }
-        );
+
+    if (queryString) {
+      await this.executeSearch(queryString);
+
+      const { hits } = this.props.items;
+      const hasOneHit = !_isEmpty(hits) && hits.length === 1;
+      if (hasOneHit && hits[0].metadata.status === 'LOANABLE') {
```
Comment (ntarocco) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: warning, it will break because now it is `CAN_CIRCULATE`

Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: Thanks!

**Review by ntarocco — DISMISSED** [review]

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js (hunk 3 above)
Comment (kpsherva) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js]: yes I would go with that.
I checked, and we are not currently ensuring the unique constraint on the barcode, I've created an issue to solve it.

File: invenio_app_ils/ui/src/invenio_app_ils/common/api/urls.js [hunk 6]
```diff
@@ -3,6 +3,7 @@ export const ApiURLS = {
     loan: '/circulation/loans/:loanPid',
     list: '/circulation/loans/',
     checkout: '/circulation/loans/checkout',
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/common/api/urls.js]: could you please remove the checkout link because it is not valid, I thought I removed it maybe it's a rebase leftover?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js [hunk 7]
```diff
@@ -37,29 +38,31 @@ export default class ItemsSearch extends Component {
...
-      return this.fetchItems(this.props.queryString);
-    }
+    queryString = queryString || this.props.queryString;
+    this.setState({ prevSearchQuery: queryString });
+
+    return this.fetchItems(queryString);
   };
 
-  _onPasteHandler = e => {
+  _onPasteHandler = async e => {
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js]: we should discuss if we use `Promise` or `await` - `async` or at least make sure to define cases in which we use one or another. 
BTW in this case what will happen if the `executeSearch` is not fulfilled?

Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js]: Yes, I agree. Should we keep using promises until we have discussed this?

If `executeSearch` would fail it would not be handled and I think an exception will be raised. For the cases where we need to catch errors it might be cleaner to use the `Promise` directly instead of wrapping code in a `try..catch`. In this case it should be fine because `this.fetchItems` already catches errors.

Comment (ntarocco) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js]: I vote for `await/async` 👍 :)

**Review by ntarocco — DISMISSED** [review]

**Review by kpsherva — DISMISSED** [review]

**Review by kpsherva — DISMISSED** [review]

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsCheckout/state/__tests__/actions.js [hunk 8]
```diff
@@ -20,7 +20,7 @@ const item = { item_pid: '2' };
 const user_pid = '2';
 const shouldForceCheckout = false;
 const doForceCheckout = true;
-const postURL = ApiURLS.loans.request;
+const postURL = ApiURLS.loans.create;
```
Comment (topless) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsCheckout/state/__tests__/actions.js]: I would use `ApiURLS.loans.create` as is, instead of renaming it to postUrl.

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js (hunk 7 above)
Comment (topless) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js]: Use a more useful name than `e` i.e. if it refers to an event, `event` is a good name for it :)

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js [hunk 9]
```diff
@@ -37,29 +38,31 @@ export default class ItemsSearch extends Component {
...
-            this.fetchUpdatedCurrentLoans(this.props.patron);
-          }
-        );
+
+    if (queryString) {
+      await this.executeSearch(queryString);
+
+      const { hits } = this.props.items;
+      const hasOneHit = !_isEmpty(hits) && hits.length === 1;
+      if (hasOneHit && hits[0].metadata.status === 'CAN_CIRCULATE') {
```
Comment (topless) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js]: You can do all the checks together for your one hit.

```
const hasOneHit = !_isEmpty(hits) && hits.length === 1 && hits[0].metadata.status === 'CAN_CIRCULATE';
if (hasOneHit) {
...
```
