### PR TITLE
LoanRequestForm: fix error and success handling on DocumentDetailsPage

### LINKED ISSUE #609: Fix error handling for LoanRequestForm
On the DocumentDetails Page the LoanRequest form should handle the response and errors by itself, and not send the success and error messages to the `<Notification>` component.
It should display a loader on the whole component while the request is being sent, and success/error message after. It should have blocked 'Request` button after the first click.

How to test/proceed:
1. Go to the frontsite, try to request a loan for a document (book/proceedings/etc)
2. try few times until there will be error response (book already requested before , for example)
3. the error appears as a notification box on the top of the page, which is not the desired behaviour. The error should be provided in a proximity of the request form.

Tasks to do
- [x]  Propose a good way to place the error message to be visible nearby the action button (The request)
- [x] Implement the solution, keeping in mind that the `<Notification/>` component is placed in one of the root components of the whole application (you can't end up with the situation that there will be 2 messages on the error displayed)
- [x] Before implementing the solution propose it first (discuss with someone)

### PR DESCRIPTION
**Pull request by KonstantinaStoikou**
* Display error message in the LoanRequestForm component and don't dispatch it to Notifications component.
Selection_002

* Display success message.
Selection_004

* Add loader.
Selection_001

Mobile view:
Selection_008
Selection_009
Selection_010

Closes #609

### CODE REVIEW

File: ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/LoanRequestForm.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ export default class LoanRequestForm extends Component {
     this.state = {
       requestEndDate: '',
       deliveryMethod: '',
+      error_message: '',
```
Comment (ntarocco) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/LoanRequestForm.js]:
```suggestion
      errorMessage: '',
```
I think prettier will complain here, in general javascript is more camelcase

File: ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/LoanRequestForm.js [hunk 2]
```diff
@@ -60,7 +68,9 @@ export default class LoanRequestForm extends Component {
     if (!isEmpty(this.state.deliveryMethod)) {
       optionalParams.deliveryMethod = this.state.deliveryMethod;
     }
-    this.props.requestLoanForDocument(documentPid, optionalParams);
+    this.props
+      .requestLoanForDocument(documentPid, optionalParams)
+      .then(() => this.handleErrorMessage());
```
Comment (ntarocco) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/LoanRequestForm.js]: It would be better to use more `redux` here, rather than this technique.
The idea is that you perform an action (request loan) that has 3 possible states:
- loading
- success, with data
- error, with data
The state is updated in redux, and then injected via props.
When props are changed, React will re-render your component.

Basically, what I am saying is that you don't need this `then` and the `handleErrorMessage` function. We can discuss tomorrow by voice! :)

File: ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/index.js [hunk 3]
```diff
@@ -2,12 +2,18 @@ import { connect } from 'react-redux';
 import LoanRequestFormComponent from './LoanRequestForm';
 import { requestLoanForDocument } from './state/actions';
 
+const mapStateToProps = state => ({
+  isLoading: state.loanRequestForm.isLoading,
```
Comment (ntarocco) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/index.js:6]: it would be nice to add `data` here to that after request success you can display "You loan request is bla bla bla...". Or maybe in another PR?

File: ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/state/actions.js [hunk 4]
```diff
@@ -18,24 +15,32 @@ export const requestLoanForDocument = (
...
+        {
+          requestExpireDate: requestEndDate,
+          requestStartDate: today,
+          deliveryMethod: deliveryMethod,
+        }
+      );
       dispatch(
         sendSuccessNotification(
           'Success!',
           `You have requested to loan this book.`
```
Comment (ntarocco) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/state/actions.js]: taking into account my comment above, this should be removed too. (maybe again another PR)

File: ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentCirculation/index.js [hunk 5]
```diff
@@ -5,6 +5,7 @@ import { showTab } from '../state/actions';
 const mapStateToProps = state => ({
   documentDetails: state.documentDetailsFront.data,
```
Comment (ntarocco) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentCirculation/index.js]: I would pass the data documentDetails from the parent component instead of redux, and here just pass (rename) `loanRequestIsLoading`

**Review by ntarocco — COMMENTED** [review]
Good job! It is starting to look much better! Thanks a lot for your changes here!

I have added a few comments, we can discuss them by voice for more details!

File: ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentCirculation/DocumentCirculation.js [hunk 6]
```diff
@@ -119,22 +119,27 @@ export default class DocumentCirculation extends Component {
...
           />
-          <Header as="h3" content="Request loan" />
-          <List>
-            <BookAvailability document={documentDetails} />
-          </List>
-          <AuthenticationGuard
-            authorizedComponent={this.renderLoanRequestForm}
-            loginComponent={this.loginToLoan}
-          />
+          <Segment basic>
```
Comment (kpsherva) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentCirculation/DocumentCirculation.js]: is this Segment needed here in the end?

File: ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentCirculation/index.js (hunk 5 above)
Comment (kpsherva) [reply ui/src/pages/frontsite/Documents/DocumentsDetails/DocumentCirculation/index.js]: @ntarocco could you explain why you prefer the props passing over redux in this case?

**Comment by ntarocco** [comment]
@KonstantinaStoikou I have rebased, squashed the 3 commits into 1 and fixed tests (it was just to update snaphosts for me. Please `git pull` from remote before changing :)

File: ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/LoanRequestForm.js [hunk 7]
```diff
@@ -30,6 +29,8 @@ export default class LoanRequestForm extends Component {
     this.state['deliveryMethod'] = this.withDeliveryMethod
       ? this.deliveryMethods[0].value
       : null;
+
+    this.props.initializeState();
```
Comment (kpsherva) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/LoanRequestForm.js:35]: in general the state is initialised by redux, was there any reason to initialise here?

Comment (ntarocco) [reply ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/LoanRequestForm.js:35]: And I would say that it should happen to `componentDidMount`, maybe there is a reason for this here.

Comment (KonstantinaStoikou) [reply ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/LoanRequestForm.js:35]: Because if I remove it from there, when I go to a document make a loan request and an error/success message appears, if I go back and forward again in the browser the message is still there.

File: ui/src/config/searchConfig.js [hunk 8]
```diff
@@ -93,6 +93,76 @@ const searchConfig = {
     },
     sortOrder: ['asc', 'desc'],
   },
+  documents_frontsite: {
```
[the remark this answers is not in the document]
Comment (KonstantinaStoikou) [reply ui/src/config/searchConfig.js]: This was a mistake by me, this change was for the issue with the restricted filter and I probably forgot to change branch. I will remove it.

**Review by topless — APPROVED** [review]

**Review by kpsherva — APPROVED** [review]

File: ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/state/actions.js [hunk 9]
```diff
@@ -18,24 +13,34 @@ export const requestLoanForDocument = (
...
+      const response = await loanApi.doRequest(
+        documentPid,
+        sessionManager.user.id,
+        {
+          requestExpireDate: requestEndDate,
+          requestStartDate: today,
+          deliveryMethod: deliveryMethod,
+        }
       );
+      dispatch({
```
Comment (ntarocco) [inline ui/src/pages/frontsite/Documents/DocumentsDetails/LoanRequestForm/state/actions.js:27]: @KonstantinaStoikou @kprzerwa for the next PR, please make sure that you add her, just before the `dispatch`, the `await delay()` to allow ES to index.
