### PR TITLE
relations: ui refactoring

### LINKED ISSUE #778: remove sequence relation does not work
Reproduce: 
1. go to on the series details page: `/backoffice/series/<pid>`
2. create a sequence relation
3. try to remove the sequence relation

if for any reason the delete endpoint is different for this relation, please unify it.

### PR DESCRIPTION
**Pull request by ntarocco**
- adds sequence deletion functionality
- re-uses DocumentTitle, DocumentEdition components in backoffice UI
- refactors relations APIs
- fixes a few misspelled components props
- fixes a few console warnings
- removes some dead code, e.g. SeriesRelations
- closes #778

relations_refactoring_frontsite_doc

relations_refactoring_backend_doc

### CODE REVIEW

**Comment by ntarocco** [comment]
I will fix conflicts when other PRs are merged

**Review by kpsherva — COMMENTED** [review]
thanks for this massive work!
as discussed in the voice call: `record_fields`-> `record_metadata`

File: ui/src/pages/frontsite/components/LiteratureRelations/LiteratureRelations.js [hunk 1]
```diff
@@ -0,0 +1,140 @@
+import React, { Component } from 'react';
```
[the remark this answers is not in the document]
Comment (ntarocco) [reply ui/src/pages/frontsite/components/LiteratureRelations/LiteratureRelations.js:1]: discussed on the voice call, to keep it like this?

File: ui/src/pages/frontsite/components/LiteratureRelations/LiteratureRelations.js [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+import _isEmpty from 'lodash/isEmpty';
+
+export class LiteratureRelations extends Component {
+  constructor(props) {
+    super(props);
+    this.relations = props.relations;
+  }
+
+  getLinkTo = relation => {
+    return relation.pid_type === 'docid'
```
[the remark this answers is not in the document]
Comment (ntarocco) [reply ui/src/pages/frontsite/components/LiteratureRelations/LiteratureRelations.js:18]: I wanted to use it, but unfortunately that one relies on the existence of the schema field.
That's why Niklas proposed to add the `pid_type` in the records too... to avoid this. If we decide to do it...

File: ui/src/api/relations/relations.js [hunk 3]
```diff
@@ -0,0 +1,59 @@
+import { http } from '@api/base';
+import {
+  add as parentChildAdd,
+  remove as parentChildRemove,
+} from './parentChild';
+import { add as siblingsAdd, remove as siblingsRemove } from './siblings';
+import { add as sequenceAdd, remove as sequenceRemove } from './sequence';
```
Comment (topless) [inline ui/src/api/relations/relations.js]: nit: in previous imports 	`import { add as addRelation, remove as removeRelation } from '@api/relations';` used the actions as prefix, `addRelation` while on this one are suffix, `siblingsAdd`, I am in favour of prefixing :) `addSiblings`, `removeSiblings`, `addSequence` and `removeSequence` wdyt?

File: ui/src/components/Document/DocumentLanguages.js [hunk 4]
```diff
@@ -1,40 +1,53 @@
...
-      </>
-    );
+export const DocumentLanguages = ({
+  metadata,
+  separator,
+  withLabel,
+  listItemAs,
+}) => {
+  const languages = _get(metadata, 'languages', []);
+  if (!languages.length) {
```
Comment (topless) [inline ui/src/components/Document/DocumentLanguages.js:13]: `isEmpty` like everywhere else, instead of length comparison?

File: ui/src/components/Document/DocumentTitle.js [hunk 5]
```diff
@@ -1,19 +1,54 @@
...
+   * title (edition)
+   * title (year)
+   * title
+   */
+  const editionYearCmp =
+    edition && year ? (
+      <>
+        {'('}
+        <DocumentEdition metadata={metadata} /> - {year}
+        {')'}
```
Comment (topless) [inline ui/src/components/Document/DocumentTitle.js:21]: Is this valid `(<DocumentEdition metadata={metadata} /> - {year})`?

File: ui/src/components/ResultsTable/ResultsTableBody.js [hunk 6]
```diff
@@ -14,7 +14,7 @@ export default class ResultsTableBody extends Component {
 
   renderRow = (columns, rows) => {
     return rows.map((row, rowIndex) => {
-      const identifier = row.pid ? row.pid : row.id;
+      const identifier = row.pid ? row.pid : row.id ? row.id : row.pid_value;
```
Comment (topless) [inline ui/src/components/ResultsTable/ResultsTableBody.js:17]: Maybe we can address this in a serializer level so we don't see these comparisons around.

File: ui/src/pages/backoffice/Series/SeriesDetails/components/SeriesRelations/RelationSequence/RelationSequence.js [hunk 7]
```diff
@@ -26,62 +33,59 @@ export default class RelationSequence extends Component {
...
-  };
-
   render() {
     const { relations, showMaxRows, isLoading, error } = this.props;
-    const next = relations['next'] || [];
-    const previous = relations['previous'] || [];
+
+    const sequenceRelations = _get(relations, 'sequence', []);
+    const continuations = sequenceRelations.filter(
+      rel => rel.relation_order === 'is_continued_by'
```
Comment (topless) [inline ui/src/pages/backoffice/Series/SeriesDetails/components/SeriesRelations/RelationSequence/RelationSequence.js:49]: does it make sense for `is_continued_by` and `continuous` to be part of the config?

File: ui/src/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js [hunk 8]
```diff
@@ -34,82 +35,43 @@ export class SeriesListEntry extends Component {
...
+      .join(' OR ');
     return (
       <>
         <Item.Description>
           <List verticalAlign={'middle'} className={'series-relations'}>
-            {!_isEmpty(series.metadata.relations.serial) && (
+            {partOfMMQuery && (
               <List.Item>
-                <List.Content>
+                <List.Content floated="right">
```
Comment (topless) [inline ui/src/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js:55]: @kprzerwa any opinion on this?

File: ui/src/pages/frontsite/components/LiteratureRelations/LiteratureRelations.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (kpsherva) [reply ui/src/pages/frontsite/components/LiteratureRelations/LiteratureRelations.js:1]: a yes, sorry it was a comment written before the call, I didn't remove it

File: ui/src/pages/frontsite/components/LiteratureRelations/LiteratureRelations.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (kpsherva) [reply ui/src/pages/frontsite/components/LiteratureRelations/LiteratureRelations.js:18]: let's leave it for now, it is already a lot of work here. we can keep it in mind for when we will have everywhere the same `pid` object

**Review by topless — APPROVED** [review]

File: ui/src/components/Document/DocumentLanguages.js (hunk 4 above)
Comment (ntarocco) [reply ui/src/components/Document/DocumentLanguages.js:13]: honestly, where we can use plain javascript, let's go with vanilla! :)

File: ui/src/api/relations/relations.js (hunk 3 above)
Comment (ntarocco) [reply ui/src/api/relations/relations.js]: done

File: ui/src/components/Document/DocumentTitle.js (hunk 5 above)
Comment (ntarocco) [reply ui/src/components/Document/DocumentTitle.js:21]: not in JSX unfortunately, the `(` is user for the language, otherwise I would have fixed that ugliness!

File: ui/src/components/Document/DocumentTitle.js [hunk 9]
```diff
@@ -1,19 +1,54 @@
...
+    ) : year ? (
+      `(${year})`
+    ) : (
+      ''
+    );
+  return editionYearCmp;
+};
+
+export const DocumentTitle = ({ metadata, titleOnly, truncate }) => {
+  const title = _get(metadata, 'title', 'No title set!');
```
[the remark this answers is not in the document]
Comment (ntarocco) [reply ui/src/components/Document/DocumentTitle.js:38]: This should never happen since it is mandatory in the schema and you cannot add/update records without it, neither during migration. If it happens, you should really check!

File: ui/src/components/ResultsTable/ResultsTableBody.js (hunk 6 above)
Comment (ntarocco) [reply ui/src/components/ResultsTable/ResultsTableBody.js:17]: yes! We will, I didn't want to start changing this too... I agree with you

File: ui/src/pages/backoffice/Series/SeriesDetails/components/SeriesRelations/RelationSequence/RelationSequence.js (hunk 7 above)
Comment (ntarocco) [reply ui/src/pages/backoffice/Series/SeriesDetails/components/SeriesRelations/RelationSequence/RelationSequence.js:49]: It might be... but it is not configurable, so it might be misleading to have it there.

File: ui/src/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js (hunk 8 above)
Comment (kpsherva) [reply ui/src/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js:55]: you probably mean that there is styling here?
I'm ok with that, because it is a semantic-ui prop, so IMO it is correct to first change it by props and then only as a last resort to overwrite the theme (which is not needed here)
