### PR TITLE
ui: notifications on errors

### LINKED ISSUE #194: Errors management for the UI
We will try to have our react application to be as agnostic as possible to the backend API errors. It will render by default the code and the error description provided with the ability to override the description providing specific actions to the user.

### LINKED ISSUE #225: UI: Fetching in children component when parent fails
When the parent component's API call fails and there is a child component dependant on the parent's data, then the error is not handled. It should not proceed to rendering the child when the parent component has an error.
Example behaviour -> turn off the backend and hit /backoffice/documents/1

### PR DESCRIPTION
**Pull request by equadon**
* notifications component using redux
* removed action loading and error states
* reducers now store error data in error and not in data
* show either notifications or error content
* redux action to clear all errors
* helper functions to send notifications
* auto-dismissable notifications with the `autoDismiss` prop
* support for error boundaries in Error component
* fix issues in #198 (`ItemSearch` class name, response type, tests)
* closes #194 
* closes #225 

Before https://github.com/inveniosoftware/invenio-records-editor-js/issues/13 was mentioned as done but this PR won't address that since it will have to be implemented in `invenio-records-editor`.

Screenshot of error and success notifications:
alt text

Screenshot of when an error boundary is used around _Pending loan requests_ where an error occurred while rendering the component:
alt text

### CODE REVIEW

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/__tests__/reducer.js [hunk 1]
```diff
@@ -38,51 +38,8 @@ describe('Fetch loan details reducer', () => {
     expect(reducer(initialState, action)).toEqual({
       ...initialState,
       isLoading: false,
-      data: 'Error',
+      error: 'Error',
       hasError: true,
     });
   });
 });
-
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/__tests__/reducer.js:46]: why do we remove all of those tests?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/types.js [hunk 2]
```diff
@@ -1,6 +1,3 @@
 export const IS_LOADING = 'fetchLoanDetails/IS_LOADING';
 export const SUCCESS = 'fetchLoanDetails/SUCCESS';
 export const HAS_ERROR = 'fetchLoanDetails/HAS_ERROR';
-export const ACTION_IS_LOADING = 'performLoanAction/IS_LOADING';
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/types.js:4]: how is now the loan action handled?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/actions.js [hunk 3]
```diff
@@ -1,13 +1,10 @@
-import {
-  IS_LOADING,
-  SUCCESS,
-  HAS_ERROR,
-  ACTION_IS_LOADING,
-  ACTION_SUCCESS,
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/actions.js:6]: `fetchLoanDetails` and `performLoanAction` are using the same types?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsCheckout/ItemsCheckout.js [hunk 4]
```diff
@@ -12,24 +11,14 @@ export default class ItemsCheckout extends Component {
...
-      <Message color="green" data-test="success">
-        The new loan was created.
-      </Message>
-    );
+    const { isLoading, error } = this.props;
 
     return (
       <Loader isLoading={isLoading}>
-        <Error error={errorData}>
-          {_isEmpty(data) ? messageInfo : messageSuccess}
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsCheckout/ItemsCheckout.js:32]: thanks for putting a notification here 🚀

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js [hunk 5]
```diff
@@ -15,7 +15,7 @@ import { Error, Loader } from '../../../../../common/components';
 import { ResultsList as ItemsResultsList } from './components';
 import _isEmpty from 'lodash/isEmpty';
 
-export default class ItemsCheckout extends Component {
+export default class ItemsSearch extends Component {
```
Comment (kpsherva) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js:18]: thanks!

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/__tests__/reducer.js (hunk 1 above)
Comment (topless) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/__tests__/reducer.js:46]: I mistakenly did that, actually they shouldn't be removed just change the types from `ACTION_*` to `IS_LOADING`, `HAS_ERROR` etc..

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/actions.js (hunk 3 above)
Comment (topless) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/actions.js:6]: We removed the explicit action types and delegated everything to loanDetails as you spotted. We believe there is no particular reason for having them since the errors will point to the actual problem that was raised. Also the UI doesn't break with a spinner in the middle of LoanDetails. Please feel free to express your concerns!

File: invenio_app_ils/ui/src/invenio_app_ils/common/components/Notifications/state/reducer.js [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+    case REMOVE:
+      const notificationId = action.payload;
+      return {
+        ...state,
+        notifications: state.notifications.filter(n => n.id !== notificationId),
+      };
+    case CLEAR_ALL:
+      return {
+        ...state,
+        notifications: [],
```
[the remark this answers is not in the document]
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/common/components/Notifications/state/reducer.js:27]: Any benefit of resetting the next id? I decided not to reset it to completely eliminate any chance of inconsistencies with previously used IDs. It shouldn't happen but it felt like the safer choice. What do you think?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js [hunk 7]
```diff
@@ -31,14 +31,14 @@ describe('PatronLoans tests', () => {
...
-        items={[]}
+        items={{ hits: [] }}
         queryString={''}
         updateQueryString={mockedUpdateString}
         fetchItems={mockedFetchItems}
         fetchPatronCurrentLoans={mockedFetchCurrent}
         clearResults={mockedClear}
         checkoutItem={mockedCheckoutItem}
-        patron={'2'}
+        patron={2}
```
Comment (topless) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js]: Should this one be a string?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js [hunk 8]
```diff
@@ -51,9 +51,11 @@ describe('PatronLoans tests', () => {
     const mockedClear = jest.fn();
     const mockedCheckoutItem = jest.fn();
 
-    const items = [
-      { item_pid: '4', barcode: '3', document_pid: 4, status: 'LOANABLE' },
-    ];
+    const items = {
+      hits: [
+        { item_pid: '4', barcode: '3', document_pid: 4, status: 'LOANABLE' },
```
Comment (topless) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js]: document_pid also a string, we are struggling a lot with the mix of integers and strings for the pids, we will have to address this on a project level.

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js [hunk 9]
```diff
@@ -64,14 +66,16 @@ describe('PatronLoans tests', () => {
         fetchPatronCurrentLoans={mockedFetchCurrent}
         clearResults={mockedClear}
         checkoutItem={mockedCheckoutItem}
-        patron={'2'}
+        patron={2}
```
Comment (topless) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js]: Possible string here too

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/__snapshots__/ItemsSearch.js.snap [hunk 10]
```diff
@@ -91,23 +75,25 @@ exports[`PatronLoans tests should load the ItemsSearch component 1`] = `
...
-        "document_pid": 4,
-        "item_pid": "4",
-        "status": "LOANABLE",
-      },
-    ]
+    Object {
+      "hits": Array [
+        Object {
+          "barcode": "3",
+          "document_pid": 4,
```
Comment (topless) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/__snapshots__/ItemsSearch.js.snap]: And here strings for the win, and I am going to stop flooding the review with string comments, so it goes for everything further down.

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/__tests__/PatronCurrentLoans.js [hunk 11]
```diff
@@ -27,7 +27,7 @@ describe('PatronLoans tests', () => {
     const component = shallow(
       <PatronCurrentLoans
         history={() => {}}
-        data={[]}
+        data={{}}
```
Comment (topless) [inline invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/__tests__/PatronCurrentLoans.js]: Maybe `data={}` is enough

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/__tests__/reducer.js (hunk 1 above)
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/__tests__/reducer.js]: All `ACTION_*` types were removed in favor of using `IS_LOADING`, `SUCCESS`, `HAS_ERROR` since we saw no need to differentiate between those types anymore.

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/types.js (hunk 2 above)
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/types.js]: Since both loan actions and the other still update the same data and even if it's an action causing something we still want the component to be in a loading state so they all use the same types. @topless do you have something to add to why this decision was made?

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js (hunk 8 above)
Comment (kpsherva) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js]: everywhere it is string except for user where the API returns a number, and maybe we should just serialize that when we get the response. The problem is coming from the fact that the user is not a record.

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/__tests__/PatronCurrentLoans.js (hunk 11 above)
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/__tests__/PatronCurrentLoans.js]: I think we need to keep this since `data` is marked as a required prop in `PatronCurrentLoans` and JSX will complain if we pass nothing.

But for the future we might want to make `data` optional and make sure all components work with empty data which would fix #225 .

File: invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/__tests__/reducer.js (hunk 1 above)
Comment (equadon) [reply invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/state/__tests__/reducer.js:46]: Those tests should be removed, right? There are already identical tests for `IS_LOADING`, `HAS_ERROR` etc.

**Review by topless — APPROVED** [review]

**Review by kpsherva — APPROVED** [review]
