### PR TITLE
acq: orders sorting

### LINKED ISSUE #672: backoffice: purchase order search sort broken
http://localhost:3000/backoffice/acquisition/orders?q=&sort=received_date&order=desc&p=1&s=10 the sort is broken

Different sort options (asc/desc)

- [x] Order Date
- [x] Grand Total (in main currency)
- [x] ~Delivery Date~ -> Received Date
- [x] Expected Delivery Date
- [x] Best Match  (I am not sure this is needed)

### PR DESCRIPTION
**Pull request by topless**
- changed naming of delivery date to received
- changed results per page to match default Elastic results (10) so SearchResultsPerPage isn't broken in first render
- cleaned unused imports
- fixed sorting for grand total in main currency, also added currency indication to make it more clear
- display grand total on an alternative currency only if its available
- defaultResultSize inside Pagination and ResultTable components instead of explicit default in every instance
- defaultResultSize for QueryBuildHelper, which fixes the ResulstPerPage components
- closes #672

### CODE REVIEW

**Review by ntarocco — APPROVED** [review]

File: ui/src/config/searchConfig.js [hunk 1]
```diff
@@ -4,16 +4,16 @@ import merge from 'lodash/merge';
...
-    text: '30',
-    value: 30,
+    text: '25',
+    value: 15,
   },
   {
-    text: '60',
-    value: 60,
+    text: '50',
+    value: 30,
```
Comment (equadon) [inline ui/src/config/searchConfig.js]: The text and the value should match

**Review by equadon — APPROVED** [review]

File: ui/src/pages/backoffice/components/OrderList/OrderListEntry.js [hunk 2]
```diff
@@ -30,8 +30,14 @@ export default class OrderListEntry extends Component {
...
           </Link>
         </Item.Description>
+        {order.metadata.grand_total.currency !== order.metadata.grand_total_main_currency.currency && (
+          <Item.Description>
+            <label>grand total</label> {formatPrice(order.metadata.grand_total)}
+          </Item.Description>
+        )}
         <Item.Description>
-          <label>total</label> {formatPrice(order.metadata.grand_total)}
+          <label>grand total</label>{' '}
```
Comment (zzacharo) [inline ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: `{' '}` is this prettier thing or is it intended?

File: ui/src/pages/backoffice/components/OrderList/OrderListEntry.js [hunk 3]
```diff
@@ -30,8 +30,14 @@ export default class OrderListEntry extends Component {
             {order.metadata.vendor.name}
           </Link>
         </Item.Description>
+        {order.metadata.grand_total.currency !== order.metadata.grand_total_main_currency.currency && (
```
Comment (zzacharo) [inline ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: Just to understand, is this meant to be `if...else` conditional rendering or just render the below label in case the condition is satisfied? I am asking because the label for both `<Item.Description>` elements is `grand total`

File: ui/src/pages/backoffice/components/OrderList/OrderListEntry.js (hunk 2 above)
Comment (topless) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: @zzacharo this is prettier, we can use `&nbsp;` if you prefer

File: ui/src/pages/backoffice/components/OrderList/OrderListEntry.js (hunk 3 above)
Comment (topless) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: @zzacharo this is conditional display, show it only if the currencies are different. Indeed the label is the same, but the currencies differentiate them and looks like this
Screenshot 2020-01-07 13 30 09

File: ui/src/pages/backoffice/components/OrderList/OrderListEntry.js (hunk 2 above)
Comment (zzacharo) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: No but I think is fine to remove it, no?

File: ui/src/pages/backoffice/components/OrderList/OrderListEntry.js (hunk 3 above)
Comment (zzacharo) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: Isn't it better to just put the default currency in parenthesis in case it's different than the order currency? Like `70.91 USD (72 CHF)`?

Comment (ntarocco) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: Now that I see it, please do not display "grand" total to the user: this is more a technical term, I doubt you ever saw it in an e-commerce website...

Comment (topless) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: I think I would put them the other way around, because everybody will have default currency

`grand total 80 CHF (75 EUR)`

Comment (topless) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: @ntarocco I changed it in order to reflect the sort option from the dropdown, I will change the dropdown too, to display `Total` instead of `Grand Total`

File: ui/src/pages/backoffice/components/OrderList/OrderListEntry.js (hunk 2 above)
Comment (topless) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: total139.41 CHF(126.74 €)

@zzacharo it will look like this then

Comment (zzacharo) [reply ui/src/pages/backoffice/components/OrderList/OrderListEntry.js]: @topless then you can use something like : \<label>\`total ${formatPrice(...)}\`\</label>. It should do the trick no?

**Comment by topless** [comment]
Screenshot 2020-01-07 13 49 38
